from enum import Enum


class GameMode(Enum):
    """
    Game modes:

    - HUMAN_VS_HUMAN: Two human players.
    - HUMAN_VS_AI: Human vs AI.
    - AI_VS_AI: Two AIs play automatically.
    """

    HUMAN_VS_HUMAN = "HUMAN_VS_HUMAN"
    HUMAN_VS_AI = "HUMAN_VS_AI"
    AI_VS_AI = "AI_VS_AI"


class PlayerType(Enum):
    """
    Player types:

    - HUMAN: User input.
    - AI: Generated by AI.
    """

    HUMAN = "HUMAN"
    AI = "AI"


class Move(Enum):
    """
    Game moves.
    """

    ROCK = "ROCK"
    PAPER = "PAPER"
    SCISSORS = "SCISSORS"


class Result(Enum):
    """
    Round result (from player1's view):

    - WIN: Player 1 wins.
    - LOSE: Player 1 loses and Player 2 wins.
    - DRAW: Tie.
    """

    WIN = "WIN"
    LOSE = "LOSE"
    DRAW = "DRAW"
